version: 0.2

env:
  variables:
    IMAGE_NAME: springboot-app
    DOCKER_HUB_USER: your-dockerhub-username
    DOCKER_HUB_REPO: your-dockerhub-username/springboot-app
  secrets-manager:
    DOCKER_HUB_PASS: dockerhub/credentials:password   # Store in Secrets Manager
    SONAR_TOKEN: sonarqube/credentials:token          # Store SonarQube token in Secrets Manager

phases:
  install:
    runtime-versions:
      java: corretto17
      docker: 20
    commands:
      - echo "Installing Maven..."
      - mvn -v
      - java -version
      - docker -v

  pre_build:
    commands:
      - echo "Logging in to Docker Hub..."
      - echo $DOCKER_HUB_PASS | docker login -u $DOCKER_HUB_USER --password-stdin
      - echo "Running Unit Tests..."
      - mvn clean verify
      - echo "Running SonarQube analysis..."
      - mvn sonar:sonar \
          -Dsonar.projectKey=springboot-app \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=$SONAR_TOKEN

  build:
    commands:
      - echo "Building JAR..."
      - mvn clean package -DskipTests
      - echo "Building Docker Image..."
      - docker build -t $IMAGE_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION .
      - docker tag $IMAGE_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION $DOCKER_HUB_REPO:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker tag $IMAGE_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION $DOCKER_HUB_REPO:latest

  post_build:
    commands:
      - echo "Pushing Docker image to Docker Hub..."
      - docker push $DOCKER_HUB_REPO:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker push $DOCKER_HUB_REPO:latest
      - echo "Build completed successfully!"

artifacts:
  files:
    - target/*.jar
